<a href="https://colab.research.google.com/github/AravindNagaraju/Guvi/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.array([10, 20, 30, 40, 50])
print(x.size)
print(x.itemsize)

5
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = np.arange(10, 50)
print(x[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x = np.arange(0, 9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x = np.array([1, 2, 0, 0, 4, 0])
print(np.nonzero(x))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.random([3, 3, 3])

array([[[0.3894969 , 0.13793314, 0.34035011],
        [0.66825364, 0.55515339, 0.1314419 ],
        [0.96964829, 0.03272063, 0.64526468]],

       [[0.07671342, 0.62619047, 0.59120291],
        [0.7474419 , 0.75998827, 0.6274952 ],
        [0.86661688, 0.54235825, 0.56219989]],

       [[0.69605753, 0.87613785, 0.86051966],
        [0.68908994, 0.79691619, 0.68233176],
        [0.29327814, 0.82805255, 0.3524994 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.random([10, 10])
print(x)
print("min value is : ", np.min(x))
print("max value is : ", np.max(x))

[[0.77193045 0.585415   0.58706963 0.79072244 0.50951926 0.48119752
  0.03133231 0.03789188 0.34384888 0.17916715]
 [0.31523898 0.48736364 0.73297216 0.54840808 0.59464769 0.40527008
  0.50595651 0.77916284 0.48506884 0.0510032 ]
 [0.61800357 0.45996926 0.12173982 0.8008025  0.53313213 0.40780074
  0.05753664 0.42304303 0.56947649 0.94878843]
 [0.13811298 0.95070755 0.95351148 0.89745724 0.10670876 0.09899691
  0.64575387 0.41241728 0.31221062 0.56379695]
 [0.49367336 0.28460524 0.20161234 0.61879428 0.66744141 0.02196445
  0.10250862 0.66014693 0.90557935 0.24558784]
 [0.25833928 0.0155443  0.75584279 0.32859241 0.7009971  0.04568063
  0.78433459 0.28988562 0.04240762 0.85328487]
 [0.32196739 0.73303078 0.60621227 0.17005813 0.0634422  0.42051729
  0.23030161 0.56056757 0.41670232 0.96098582]
 [0.86345579 0.5069143  0.34465174 0.19215628 0.15039154 0.39870297
  0.77659186 0.81615502 0.64260431 0.6289066 ]
 [0.29779018 0.70915571 0.78946196 0.19513268 0.5209276  0.75217316
  0.14948791

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x = np.random.random(10)
print(np.mean(x))

0.6605737404914335


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.pad(arr, (1, ), 'constant', constant_values = (0))

array([0, 1, 2, 3, 4, 5, 0])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
np.diag(np.arange(4) + 1, k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
a = np.ones((8, 8), dtype = int)    
a[1::2, ::2] = 0                    
a[::2, 1::2] = 0                    
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(100, (6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
arr = np.array([[1, 0], [0, 1]])    
chess = np.tile(arr,(4,4))          
print(chess)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
a = np.random.random((5, 5))
min = a.min()
max = a.max()
norm = (a - min)/(max - min)
print(norm)

[[0.39713522 0.07709034 0.83575493 0.35631726 0.23973324]
 [0.92158283 0.1850449  0.         0.47046694 1.        ]
 [0.36619336 0.38846358 0.85100978 0.19731061 0.69313734]
 [0.20765116 0.00646893 0.12796875 0.61785463 0.16680565]
 [0.86444736 0.59537245 0.57710552 0.57047212 0.77787989]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
prod = np.dot(np.random.randint(low = 100, size =(5, 3)), np.random.randint(low = 100, size =(3, 2)))
display(prod)

array([[6782, 6415],
       [3970, 3549],
       [5126, 4756],
       [6623, 7761],
       [7910, 8271]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
a = np.arange(10)
for i in range(len(a)):
    if a[i] > 3 and a[i] < 8:
        a[i] = a[i]*-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Z**Z: negative powers invalid. Also given vector Z, it can be multiplied with its transpose.



#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
a = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(a)), a))

[ -9.  -7.  -3.   8.  -4.  -5. -10.  -1.   4.  -4.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a = np.random.randint(0, 5, 5)
b = np.random.randint(0, 5, 5)
print(np.intersect1d(a, b))

[0 1]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
if np.sqrt(-1) == np.emath.sqrt(-1):
    print("True")
else:
    print("False")

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
print("Yesterday: ", np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print("Today: ", np.datetime64('today', 'D'))
print("Tomorrow", np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

Yesterday:  2022-08-07
Today:  2022-08-08
Tomorrow 2022-08-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
a = np.random.uniform(0,10,10)

print(a - a%1)
print(np.floor(a))
print(np.ceil(a)-1)
print(a.astype(int))
print(np.trunc(a))

[0. 6. 1. 2. 4. 0. 3. 3. 1. 2.]
[0. 6. 1. 2. 4. 0. 3. 3. 1. 2.]
[0. 6. 1. 2. 4. 0. 3. 3. 1. 2.]
[0 6 1 2 4 0 3 3 1 2]
[0. 6. 1. 2. 4. 0. 3. 3. 1. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
a = np.zeros((5, 5))
a = a + np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
np.fromiter(generate(),dtype=float, count = -1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
vec = np.random.random(10)
vec.sort()
print(vec)

[0.00265251 0.04094654 0.10994247 0.1450381  0.38781235 0.38864362
 0.5051957  0.59849382 0.65216259 0.67651278]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [3]:
a = np.random.randint(low = 10, size = 10)
np.add.reduce(a)

44

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [9]:
a = np.random.randint(0,5,5)
b = np.random.randint(0,5,5)

if not np.allclose(a, b) and not np.array_equal(a, b):
    print("Arrays not equal")

else:
    print("Arrays are equal")

Arrays not equal


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [11]:
a = np.random.randint(0,5,5)

a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [12]:
f = np.random.random((10, 2))
x, y = f[:, 0], f[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print(r)
print(theta)

[0.34311184 0.51207754 0.68900757 1.31635241 0.49323361 0.83532591
 0.03478475 0.5879039  0.8116356  0.13535472]
[0.55584351 0.84486533 1.46350858 0.78912992 0.50080517 1.49890107
 0.1695349  0.59349526 0.7508633  0.04459877]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [13]:
v = np.random.random(10)
v[v.argmax()] = 0
v

array([0.83604186, 0.250391  , 0.52372834, 0.52867409, 0.        ,
       0.51410808, 0.11057152, 0.88627958, 0.92489036, 0.01096171])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [21]:
Z = np.zeros((11, 11), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,11), np.linspace(0,1,11))
print(Z)

[[(0. , 0. ) (0.1, 0. ) (0.2, 0. ) (0.3, 0. ) (0.4, 0. ) (0.5, 0. )
  (0.6, 0. ) (0.7, 0. ) (0.8, 0. ) (0.9, 0. ) (1. , 0. )]
 [(0. , 0.1) (0.1, 0.1) (0.2, 0.1) (0.3, 0.1) (0.4, 0.1) (0.5, 0.1)
  (0.6, 0.1) (0.7, 0.1) (0.8, 0.1) (0.9, 0.1) (1. , 0.1)]
 [(0. , 0.2) (0.1, 0.2) (0.2, 0.2) (0.3, 0.2) (0.4, 0.2) (0.5, 0.2)
  (0.6, 0.2) (0.7, 0.2) (0.8, 0.2) (0.9, 0.2) (1. , 0.2)]
 [(0. , 0.3) (0.1, 0.3) (0.2, 0.3) (0.3, 0.3) (0.4, 0.3) (0.5, 0.3)
  (0.6, 0.3) (0.7, 0.3) (0.8, 0.3) (0.9, 0.3) (1. , 0.3)]
 [(0. , 0.4) (0.1, 0.4) (0.2, 0.4) (0.3, 0.4) (0.4, 0.4) (0.5, 0.4)
  (0.6, 0.4) (0.7, 0.4) (0.8, 0.4) (0.9, 0.4) (1. , 0.4)]
 [(0. , 0.5) (0.1, 0.5) (0.2, 0.5) (0.3, 0.5) (0.4, 0.5) (0.5, 0.5)
  (0.6, 0.5) (0.7, 0.5) (0.8, 0.5) (0.9, 0.5) (1. , 0.5)]
 [(0. , 0.6) (0.1, 0.6) (0.2, 0.6) (0.3, 0.6) (0.4, 0.6) (0.5, 0.6)
  (0.6, 0.6) (0.7, 0.6) (0.8, 0.6) (0.9, 0.6) (1. , 0.6)]
 [(0. , 0.7) (0.1, 0.7) (0.2, 0.7) (0.3, 0.7) (0.4, 0.7) (0.5, 0.7)
  (0.6, 0.7) (0.7, 0.7) (0.8, 0.7) (0.9, 0.7) (1. 

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [29]:
x = np.arange(10)
y = x + 0.5
c = 1/np.subtract.outer(x, y)
c

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333, -0.11764706, -0.10526316],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615, -0.13333333, -0.11764706],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818, -0.15384615, -0.13333333],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222, -0.18181818, -0.15384615],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429, -0.22222222, -0.18181818],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [30]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [32]:
a = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(a-v)).argmin()
print(a[index])

80


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [3]:
position = ('position', [ ('x', float),('y', float)])
color = ('color', [('r', float), ('g', float), ('b', float)])
array = np.zeros(10,[position, color])
print(array)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [5]:
p = np.random.random((10,2))
x, y = np.atleast_2d(p[:,0], p[:,1])
dis = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(dis)

[[0.         0.89080456 0.38516251 0.58680251 0.42331438 0.91697149
  0.49532766 0.60763359 0.16209838 0.83850015]
 [0.89080456 0.         1.034411   0.72263216 0.57984368 0.14846221
  0.41973648 0.63111421 0.772931   0.1907556 ]
 [0.38516251 1.034411   0.         0.94936632 0.45507911 1.00374804
  0.62002526 0.50366728 0.52042561 1.05035484]
 [0.58680251 0.72263216 0.94936632 0.         0.70141141 0.83658532
  0.594915   0.90834805 0.43156758 0.55954556]
 [0.42331438 0.57984368 0.45507911 0.70141141 0.         0.5534253
  0.17661997 0.21550378 0.40403466 0.61400692]
 [0.91697149 0.14846221 1.00374804 0.83658532 0.5534253  0.
  0.42300062 0.55342023 0.81960534 0.33579006]
 [0.49532766 0.41973648 0.62002526 0.594915   0.17661997 0.42300062
  0.         0.33060291 0.41509943 0.43770265]
 [0.60763359 0.63111421 0.50366728 0.90834805 0.21550378 0.55342023
  0.33060291 0.         0.61430161 0.72196462]
 [0.16209838 0.772931   0.52042561 0.43156758 0.40403466 0.81960534
  0.41509943 0.614301

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [8]:
arr = np.arange(10, dtype=np.float32)
print(arr.astype(np.int32))

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [17]:
from io import StringIO

str1 = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
str2 = np.genfromtxt(str1, delimiter=",")
print(str2)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [19]:
arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(arr):
    print(index, value)
print("\n")
for index in np.ndindex(arr.shape):
    print(index, arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [21]:
sigma, mu = 1.0, 0.0

x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
dis = np.sqrt(x*x + y*y)

Gauss = np.exp(-( (dis - mu)**2 / ( 2.0 * sigma**2 ) ) )
print(Gauss)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [25]:
n = 10
p = 3
arr = np.ones((n,n))
np.put(arr, np.random.choice(range(n*n), p), np.random.randint(low = 2, high = 5, size = 3))
print(arr)

[[1. 1. 1. 1. 3. 4. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 4. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [32]:
x = np.random.random((5, 10))
y = x - x.mean(axis = 1, keepdims = True)
print(y)

[[-0.22851466 -0.37413989  0.19761199 -0.16708415  0.18834448  0.41049941
   0.27199397 -0.38762819 -0.37345088  0.46236793]
 [-0.0988172   0.0176469   0.02797667  0.19704017 -0.38407686  0.59198108
  -0.23777899 -0.39725767 -0.1624956   0.44578149]
 [-0.30925299  0.33686294 -0.25197263  0.10355196  0.50591544 -0.35572979
   0.18260516 -0.18010722 -0.30452598  0.27265309]
 [-0.31959509  0.29951446 -0.24950994 -0.03966548 -0.31113337  0.10203329
   0.48574045  0.31789372 -0.23954275 -0.04573529]
 [ 0.08356086  0.34804363 -0.40133892 -0.38729092  0.36962116 -0.13838681
  -0.02367235  0.25508274  0.28339073 -0.38901012]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [42]:
arr = np.random.randint(0,10,(3,3))
print(arr)
print("\n")
print(arr[arr[:,2].argsort()])

[[2 4 7]
 [1 8 8]
 [5 1 6]]


[[5 1 6]
 [2 4 7]
 [1 8 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [48]:
arr = np.random.randint(0,3,(3,10))
print((~arr.any()).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [59]:
arr = np.random.randint(low = 0, high = 100, size = 5)
val = np.random.randint(100)
n = arr.flat[np.abs(arr - val).argmin()]
print(arr, "\n", val, "\n", n)

[35 80 67 35 18] 
 87 
 80


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [72]:
a = np.arange(3).reshape(3,1)
print(a, "\n")
b = np.arange(3).reshape(1,3)
print(b, "\n")
itr = np.nditer([a, b, None])
for x,y,z in itr:
    z[...] = x + y
print(itr.operands[2])

[[0]
 [1]
 [2]] 

[[0 1 2]] 

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [74]:
v = np.ones(10)
print(v, '\n')
i = np.random.randint(0,len(v),20)
print(i, '\n')

np.add.at(v, i, 1)
print(v)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[9 3 0 8 9 0 3 3 8 4 2 6 3 0 2 7 3 8 8 7] 

[4. 1. 3. 6. 2. 1. 2. 3. 5. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [76]:
x = [10, 11, 4, 6, 2, 1, 9]
i = [1, 3, 1, 3, 1, 2, 2]
f = np.bincount(i, x)
print(f)

[ 0. 16. 10. 17.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [77]:
w,h = 16,16
i = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f = i[...,0]*(256*256) + i[...,1]*256 +i[...,2]
n = len(np.unique(f))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [81]:
arr = np.random.randint(0,10,(3,4,3,4))
print(arr, '\n')
sum = arr.sum(axis=(-2,-1))
print(sum)

[[[[9 4 0 3]
   [7 6 4 5]
   [4 9 2 7]]

  [[9 7 9 0]
   [7 2 1 2]
   [0 1 9 7]]

  [[6 0 2 4]
   [2 6 3 7]
   [3 3 8 8]]

  [[3 1 2 2]
   [9 4 9 3]
   [7 4 0 6]]]


 [[[2 4 4 5]
   [8 4 1 9]
   [0 6 8 8]]

  [[6 3 5 7]
   [3 4 6 6]
   [6 2 5 9]]

  [[9 1 6 7]
   [2 8 1 8]
   [0 2 6 8]]

  [[9 4 3 9]
   [8 1 2 3]
   [2 6 6 7]]]


 [[[6 6 5 3]
   [7 4 0 8]
   [8 8 6 0]]

  [[4 5 4 9]
   [9 0 7 2]
   [8 5 7 3]]

  [[8 8 4 1]
   [8 5 8 8]
   [8 1 0 4]]

  [[5 8 4 8]
   [3 7 2 9]
   [0 7 7 9]]]] 

[[60 54 52 50]
 [59 62 58 60]
 [61 63 63 69]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [85]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.55611108 0.37202887 0.64547463 0.39948129 0.4964079  0.49930761
 0.45648306 0.50587258 0.55945521 0.42909223]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [86]:
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))

np.diag(np.dot(a, b))

array([0.83790063, 0.4872569 , 1.65625895, 0.47547292, 1.57486793])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [87]:
v = np.array([1,2,3,4,5])
n = 3
v0 = np.zeros(len(v) + (len(v)-1)*(n))
print(v0,'\n')
v0[::n+1] = v
print(v0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [88]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [91]:
arr = np.arange(9).reshape(3, 3)
print(arr,'\n')
arr[[0,1]] = arr[[1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[3 4 5]
 [0 1 2]
 [6 7 8]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

[1 1 2 3 4 4 6]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [94]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [3]:
def average(a, n = 3):
    ret = np.cumsum(a, dtype = float)
    ret[n:] = ret[n:]- ret[:-n]
    return ret[n-1:] / n
data = np.arange(20)
print(data)
print(average(data, n = 3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [5]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window +1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape = shape, strides = strides)

data = rolling(np.arange(5),3)
print(data)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [8]:
arr1 = np.random.randint(0,2,10)
print(arr1)
print(np.logical_not(arr1, out = arr1))

arr2 = np.random.uniform(-1.0,1.0,10)
print(arr2)
print(np.negative(arr2, out = arr2))

[1 0 1 1 0 0 1 0 0 1]
[0 1 0 0 1 1 0 1 1 0]
[-0.55229435  0.18047464 -0.32889568 -0.51471005  0.39061874 -0.88625225
 -0.29821218  0.14376511 -0.08639673 -0.14740205]
[ 0.55229435 -0.18047464  0.32889568  0.51471005 -0.39061874  0.88625225
  0.29821218 -0.14376511  0.08639673  0.14740205]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [9]:
def distance(P0, P1, p):
    T = P1 - P0
    print(T)
    L = (T**2).sum(axis=1)
    print(L)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    print(U)
    U = U.reshape(len(U),1)
    print(U)
    D = P0 + U*T - p
    print(D)
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(1,2))
P1 = np.random.uniform(-10,10,(1,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[[8.20112611 6.22405106]]
[105.99728103]
[0.13656222]
[[0.13656222]]
[[-5.07990249  6.69353778]]
[8.40290767]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [10]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[-10.16269517 -10.27815592]
 [  0.59502926  -9.09721897]
 [ -1.22982154  -5.62510737]
 [ 15.40406567   9.75857941]
 [-16.12411007   1.7790079 ]
 [ -2.22289997  11.53990808]
 [-10.89182771  -2.38415837]
 [ -4.49318695  10.78978671]
 [  3.03528251   0.26189157]
 [  3.58466407 -17.20314386]]
[208.92086223  83.1134529   33.15429395 332.51511124 263.15179454
 138.11076284 124.31612192 136.60822626   9.28152712 308.79797512]
[ 0.21952244 -0.74424978  0.40727275  0.86586042  0.48693967  1.14198284
  0.25310007  0.98492681 -0.99676111  0.17197955]
[[ 0.21952244]
 [-0.74424978]
 [ 0.40727275]
 [ 0.86586042]
 [ 0.48693967]
 [ 1.14198284]
 [ 0.25310007]
 [ 0.98492681]
 [-0.99676111]
 [ 0.17197955]]
[[  1.59752308  -1.57957714]
 [  1.4932702    0.09767155]
 [  5.17291793  -1.13095902]
 [  5.16391506  -8.15131828]
 [ -0.79377167  -7.19438168]
 [-10.88033301  -2.09584789]
 [  0.44673575  -2.04087483]
 [ -5.07522066  -2.11347229]
 [  1.44739806 -16.77511811]
 [ -6.6362884   -1.38282077]]
[[-10.16269

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [9]:
Z = np.random.randint(0,10,(10,10))
shape = (4,4)
fill  = 0
position = (2, 2)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 4 5 5 6 9 6 6 5 2]
 [4 0 0 3 6 2 7 8 6 7]
 [2 2 9 5 9 3 1 2 4 2]
 [6 2 2 5 4 4 6 4 6 4]
 [5 3 6 1 6 6 3 2 2 0]
 [5 5 0 3 9 5 1 7 3 2]
 [8 4 0 4 9 2 3 8 6 1]
 [3 4 8 5 9 9 3 3 1 0]
 [6 2 3 1 4 5 2 9 0 5]
 [8 5 8 0 3 4 0 9 0 8]]
[[5 4 5 5]
 [4 0 0 3]
 [2 2 9 5]
 [6 2 2 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [13]:
from numpy.lib import stride_tricks
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [17]:
Z = np.random.uniform(0,1,(10,10))
#U, S, V = np.linalg.svd(Z)
#rank = np.sum(S > 1e-10)
#print(rank)

np.linalg.matrix_rank(Z)

10

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [30]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [32]:
from numpy.lib import stride_tricks
mat = np.random.randint(0,5,(10,10))
print(mat)
n = 3
i = 1 + (mat.shape[0]-3)
j = 1 + (mat.shape[1]-3)
C = stride_tricks.as_strided(mat, shape=(i, j, n, n), strides=mat.strides + mat.strides)
print(C)

[[4 4 1 0 1 4 4 4 2 0]
 [3 3 3 0 4 3 3 4 3 1]
 [0 1 3 3 4 1 2 2 1 3]
 [2 3 2 3 0 1 1 4 2 3]
 [4 1 0 1 4 1 3 4 2 2]
 [0 3 4 1 0 2 2 1 0 2]
 [2 2 0 1 4 3 4 0 4 3]
 [3 3 3 0 0 2 2 3 0 4]
 [1 3 4 4 2 4 2 3 4 3]
 [3 2 3 4 1 3 0 2 1 0]]
[[[[4 4 1]
   [3 3 3]
   [0 1 3]]

  [[4 1 0]
   [3 3 0]
   [1 3 3]]

  [[1 0 1]
   [3 0 4]
   [3 3 4]]

  [[0 1 4]
   [0 4 3]
   [3 4 1]]

  [[1 4 4]
   [4 3 3]
   [4 1 2]]

  [[4 4 4]
   [3 3 4]
   [1 2 2]]

  [[4 4 2]
   [3 4 3]
   [2 2 1]]

  [[4 2 0]
   [4 3 1]
   [2 1 3]]]


 [[[3 3 3]
   [0 1 3]
   [2 3 2]]

  [[3 3 0]
   [1 3 3]
   [3 2 3]]

  [[3 0 4]
   [3 3 4]
   [2 3 0]]

  [[0 4 3]
   [3 4 1]
   [3 0 1]]

  [[4 3 3]
   [4 1 2]
   [0 1 1]]

  [[3 3 4]
   [1 2 2]
   [1 1 4]]

  [[3 4 3]
   [2 2 1]
   [1 4 2]]

  [[4 3 1]
   [2 1 3]
   [4 2 3]]]


 [[[0 1 3]
   [2 3 2]
   [4 1 0]]

  [[1 3 3]
   [3 2 3]
   [1 0 1]]

  [[3 3 4]
   [2 3 0]
   [0 1 4]]

  [[3 4 1]
   [3 0 1]
   [1 4 1]]

  [[4 1 2]
   [0 1 1]
   [4 1 3]]

  [[1 2 2]
   [1 1 4]
   [1 3 

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [36]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,50,(5,5)))
print(S)

[[37 36 56 29 54]
 [36 33  4 52 67]
 [56  4 11 63 25]
 [29 52 63 44 76]
 [54 67 25 76 44]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [40]:
p, n = 5, 6
M = np.random.randint(10, size=(p, n, n))
V = np.random.randint(10, size=(p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[506]
 [392]
 [611]
 [542]
 [532]
 [532]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [46]:
Z = np.random.randint(0,16,(16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[103 112 119 125]
 [117  99 151 132]
 [165  92 110 131]
 [ 96 109 126 131]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [47]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [54]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [56]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([2, 4, 6], [0, 3])))

[[2 0]
 [2 3]
 [4 0]
 [4 3]
 [6 0]
 [6 3]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [57]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [65]:
x = np.random.randint(5e7)

print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i->i',x,x,x))

-8031764849795758503
563817301435200341593


ValueError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [66]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [69]:
Z = np.random.randint(0,5,(10,3))
print(Z)
print('\n')

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 1 4]
 [3 2 2]
 [1 0 0]
 [3 0 2]
 [2 4 0]
 [0 0 0]
 [3 4 3]
 [4 0 0]
 [2 1 4]
 [0 3 1]]


[[1 1 4]
 [3 2 2]
 [1 0 0]
 [3 0 2]
 [2 4 0]
 [3 4 3]
 [4 0 0]
 [2 1 4]
 [0 3 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [70]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [73]:
arr = np.random.randint(0,2,(6,3))
print(arr, "\n")
print(np.unique(arr, axis=0))

[[1 1 1]
 [0 0 1]
 [1 0 1]
 [1 1 0]
 [0 0 0]
 [1 0 1]] 

[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [76]:
A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)

print(np.einsum('i->', A), '\n')
print(np.einsum('i,i->i', A, B), '\n')
print(np.einsum('i,i', A, B), '\n')
print(np.einsum('i,j->ij', A, B), '\n')

2.0520624753064576 

[0.00416016 0.31621819 0.0702172  0.31828503 0.4491155 ] 

1.157996069936779 

[[4.16015643e-03 2.49389392e-01 3.62905997e-01 3.46108137e-01
  1.98057222e-01]
 [5.27495222e-03 3.16218188e-01 4.60153800e-01 4.38854623e-01
  2.51130553e-01]
 [8.04931712e-04 4.82533371e-02 7.02172021e-02 6.69670527e-02
  3.83212847e-02]
 [3.82572773e-03 2.29341355e-01 3.33732531e-01 3.18285025e-01
  1.82135701e-01]
 [9.43359048e-03 5.65516570e-01 8.22927361e-01 7.84836454e-01
  4.49115498e-01]] 



#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)